#import = ["/home/tom/.config/alacritty/color.toml"]

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[font]
size = 10

[font.normal]
family = "DejaVu Sans M Nerd Font"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 1
y = 1
